// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconCarbonApps: typeof import('~icons/carbon/apps.jsx')['default']
}
export {}
