// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ActionIcon: typeof import('@mantine/core')['ActionIcon']
  const Button: typeof import('@mantine/core')['Button']
  const Card: typeof import('@mantine/core')['Card']
  const Container: typeof import('@mantine/core')['Container']
  const Grid: typeof import('@mantine/core')['Grid']
  const Group: typeof import('@mantine/core')['Group']
  const Select: typeof import('@mantine/core')['Select']
  const SimpleGrid: typeof import('@mantine/core')['SimpleGrid']
  const Text: typeof import('@mantine/core')['Text']
  const TextInput: typeof import('@mantine/core')['TextInput']
  const Title: typeof import('@mantine/core')['Title']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
export {}
